#!/bin/bash -x

# let's encrypt
#     https://gist.github.com/renchap/c093702f06df69ba5cac
# https://eblog.damia.net/2015/12/03/lets-encrypt-automation-on-debian/

if [ -z "$FIX_FRONTEND_PORT" ]; then export FIX_FRONTEND_PORT=""; fi

cnt=1
echo "****"
check_var=VHOST_${cnt}_SERVERNAME
while [ ! x"${!check_var}" == "x" ]; do
    ssl=VHOST_${cnt}_SSL
    if [ "${!ssl}" == "True" ]; then
        echo "* Process SSL for ${!check_var}"

        # https://gist.github.com/plentz/6737338
        if [ ! -f "/etc/nginx/ssl/dhparam.pem" ]; then
          mkdir -p /etc/nginx/ssl/ 2>/dev/null
          openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
        fi


        servername=VHOST_${cnt}_SERVERNAME
        domains=VHOST_${cnt}_DOMAINS

        if [ ! -f "/etc/letsencrypt/live/${!servername}/fullchain.pem" ]; then
                /certbot-master/letsencrypt-auto certonly -t -a standalone ${TEST_CERT} --standalone-supported-challenges http-01 -d ${!domains} --email ${NOTIFICATION_EMAIL} --agree-tos
                echo "* ! let's encrypted ... !"
            else
                echo "* Certificate does already exist"
                openssl x509 -in /etc/letsencrypt/live/${!servername}/fullchain.pem -noout -subject
                openssl x509 -in /etc/letsencrypt/live/${!servername}/fullchain.pem -noout -issuer
                openssl x509 -in /etc/letsencrypt/live/${!servername}/fullchain.pem -noout -dates
                openssl x509 -in /etc/letsencrypt/live/${!servername}/fullchain.pem -noout -serial
        fi
    fi

    let cnt=cnt+1
    check_var=VHOST_${cnt}_SERVERNAME
done

if [ ! -f "/env.json" ]; then
    python /env2json.py | python -m json.tool
    python /env2json.py > /env.json
    j2 /nginx.tmpl /env.json > /etc/nginx/nginx.conf
    echo "* Configuration done"
else
    echo "* Already configured"
fi


#echo "**** TEMPLATE ****"
#cat /nginx.tmpl
echo "**** Start CONFIG ****"
cat -n /etc/nginx/nginx.conf
echo "**** End CONFIG ****"
echo "* Starting nginx now..."
nginx
