#!/bin/bash

# let's encrypt
#     https://gist.github.com/renchap/c093702f06df69ba5cac
DOMAINS=${SERVER_NAME}
# https://eblog.damia.net/2015/12/03/lets-encrypt-automation-on-debian/
if [ ! -f "/etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem" ]; then
     /letsencrypt-master/letsencrypt-auto certonly -a standalone ${TEST_CERT} --standalone-supported-challenges http-01 -d ${DOMAINS} --email ${NOTIFICATION_EMAIL} --agree-tos
     echo "* ! let's encrypted ... !"
else
     echo "* Certificate does already exist"
     openssl x509 -in /etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem -noout -subject
     openssl x509 -in /etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem -noout -issuer
     openssl x509 -in /etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem -noout -dates
     openssl x509 -in /etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem -noout -serial
fi

if [ ! -f "/env.json" ]; then
    python /env2json.py | python -m json.tool
    python /env2json.py > /env.json
    j2 /nginx.tmpl /env.json > /etc/nginx/nginx.conf
    echo "* Configuration done"
else
    echo "* Already configured"
fi

# https://gist.github.com/plentz/6737338
if [ ! -f "/etc/nginx/ssl/dhparam.pem" ]; then
  mkdir -p /etc/nginx/ssl/ 2>/dev/null
  openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
fi

#echo "**** TEMPLATE ****"
#cat /nginx.tmpl
echo "**** Start CONFIG ****"
cat /etc/nginx/nginx.conf
echo "**** End CONFIG ****"
echo "* Starting nginx now..."
nginx
